# Generated by Django 3.2 on 2022-05-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='Email_confirmation',
            new_name='email_confirmation',
        ),
    ]
