# Generated by Django 3.2 on 2022-05-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20220517_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email_confirmation',
            field=models.CharField(max_length=250),
        ),
    ]
