# Generated by Django 3.2 on 2022-05-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211222_1116'),
        ('newsletter', '0003_alter_newsletter_email_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
